# Generated by Django 4.2.3 on 2023-08-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_billsent', '0002_billsent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsent',
            name='image',
            field=models.ImageField(default=1, upload_to='billsent/', verbose_name='изобржение'),
            preserve_default=False,
        ),
    ]
